### ISSUE TITLE
exe `npm run clean` on window synstem，occured the following question. then I found that source code does not support * character. how can I fix it?

### ISSUE THREAD

**Issue by Yuanbaby0077** [saqqdy/eslint-sets#134]
![image](https://user-images.githubusercontent.com/78551876/218978678-efee4b11-28fe-4235-87e6-0a9052e5035e.png)
![image](https://user-images.githubusercontent.com/78551876/218979339-c965c80c-5716-4591-8f9b-f756d8ab3c33.png)

**Comment by Yuanbaby0077** [comment]
besides replace `rimraf package/*/dist` with `rm -rf package/*/dist`

**Comment by saqqdy** [comment]
Thank you very much for raising the issue, I also found this problem, I started a new project `rm-all` to replace this tool, but I have not had time to write it recently. If you are willing to try it, please be patient for a while!
